name: flutter_jsbridge_sdk
description: A lightweight jsbridge for sending messages between flutter and javascript in WebViews.
version: 1.0.1
homepage: https://github.com/TryImpossible/flutter_jsbridge_sdk

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
